### ISSUE TITLE
Result not updating when using "velg alle" or "fjern alle"

### ISSUE THREAD

**Issue by vfaergestad** [ivannorderhaug/studentwebplus#1]
When using the "velg alle" button, the result of the average does not update.
![image](https://user-images.githubusercontent.com/49147564/213388536-0b57589c-f0c1-45c7-9e43-e84fd0705347.png)
I have to manually choose the different grades for it to update.
The "fjern alle" options does work though.

**Comment by ivannorderhaug** [comment]
Problem identified. Will fix

**Comment by sanderob** [comment]
Found the fix!

**Comment by ivannorderhaug** [comment]
Big thanks to @sanderob for identifying the issue!
